### ISSUE TITLE
Vistor Pattern

### ISSUE THREAD

**Issue by orellabac** [sebastienros/esprima-dotnet#10]
Hi are you planning to implement a Visitor PAttern on the AST. I started something like:
https://github.com/orellabac/EsprimaVisitor
but do not know if you are already working on something in this direction

**Comment by sebastienros** [comment]
I am not sure, and this is why I expose a `Type` property on each node so that you can do a switch case and invoke any other service to visit a node.

But I am not opposed to it, just that right now I didn't feel the need. If it enables a simpler story for extensibility then I assume I should probably do it.

**Comment by orellabac** [comment]
Ok. Thanks. I would explore it a little. I think it can be used to provide some kind of fluent API. I'll explore it a little.

**Comment by talweiss1982** [comment]
I didn't see this issue but now that i have, i sent this PR:
https://github.com/sebastienros/esprima-dotnet/pull/21
